site_name: 'RaspberryPi HPC cluster'
repo_url: https://github.com/matpiq/PiHPC-docs
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Hardware: hardware.md
theme:
  palette:
    - media: '(prefers-color-scheme: light)'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
# markdown_extensions:
#   - admonition
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.snippets
#   - pymdownx.tabbed
#   - pymdownx.smartsymbols
#   - footnotes
#   - attr_list
#   - def_list
#   - meta
#   - pymdownx.caret
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.highlight:
#       use_pygments: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
